<?php
declare(strict_types=1);

/**
 * Catálogo de ubicaciones HxH (region_slug => metadatos).
 * Usado por provision_hxh_forums.php y seed_locations_hxh.php.
 *
 * @return array<string, array<string, mixed>>
 */
function game_hxh_locations_catalog(): array
{
    return [
        'dark-continent' => [
            'preferred_fid' => 2,
            'disporder' => 99,
            'name' => 'Continente Oscuro',
            'region_slug' => 'dark-continent',
            'country' => 'Ninguno (Tierras Salvajes Inexploradas)',
            'travel_difficulty' => 5,
            'island_image' => 'images/game/locations/dark_continent.svg',
            'leader_name' => 'Guías del Portal',
            'description' => 'El vasto y peligroso mundo exterior que rodea al Lago Mobius. Es una tierra inexplorada habitada por calamidades capaces de extinguir la humanidad entera, y recursos míticos inimaginables.',
            'terrain' => 'Terrenos alienígenas gigantescos, ruinas prehistóricas, pantanos de la muerte',
            'climate' => 'Extremo y caótico',
            'climate_temp' => '-10 a 50°C',
            'climate_wind' => 'Tormentas de viento de escala continental',
            'climate_precip' => 'Torrencial, lluvias ácidas',
            'buildings' => 'Ruinas de la Ciudad de Oro, El Árbol del Mundo Real, Laberinto de las Calamidades',
            'defenses' => 'Las Cinco Grandes Calamidades (Brion, Ai, Pap, Zoae, Hellbell)',
            'resources' => 'Hierbas medicinales divinas (Nitro Rice), metales maravillosos (Unbium), agua milagrosa',
            'coord_x' => 800,
            'coord_y' => 800,
            'base_danger' => 5,
        ],
        'whale-island' => [
            'preferred_fid' => 4,
            'disporder' => 1,
            'name' => 'Isla Ballena',
            'region_slug' => 'whale-island',
            'country' => 'Ninguno (Aislada)',
            'travel_difficulty' => 1,
            'island_image' => 'images/game/locations/whale_island.svg',
            'leader_name' => 'Mito Freecss',
            'description' => 'Una pequeña y pintoresca isla rural en forma de ballena. Sus habitantes viven principalmente de la pesca y el campo. Es famosa por ser el hogar de infancia de Gon Freecss.',
            'terrain' => 'Bosques densos, lagos cristalinos, montañas suaves',
            'climate' => 'Templado marítimo',
            'climate_temp' => '15 a 28°C',
            'climate_wind' => 'Brisas marinas suaves',
            'climate_precip' => 'Moderada, lluvias primaverales',
            'buildings' => 'Casa de Mito Freecss, Puerto Pesquero, El Árbol Gigante, Mercado Local',
            'defenses' => 'Milicia local (pescadores), terreno boscoso difícil de navegar',
            'resources' => 'Peces exóticos (Rey del Pantano), hierbas medicinales, madera de roble, cultivos locales',
            'coord_x' => 200,
            'coord_y' => 350,
            'base_danger' => 1,
        ],
        'padokea' => [
            'preferred_fid' => 5,
            'disporder' => 2,
            'name' => 'República de Padokea',
            'region_slug' => 'padokea',
            'country' => 'República de Padokea',
            'travel_difficulty' => 2,
            'island_image' => 'images/game/locations/padokea.svg',
            'leader_name' => 'Presidente Netero',
            'description' => 'Una nación democrática altamente desarrollada, hogar de la bulliciosa Ciudad Examen y del imponente Coliseo de la Celestial (Heavens Arena), el epicentro de las batallas de artes marciales.',
            'terrain' => 'Llanuras urbanas, rascacielos gigantescos, colinas bajas',
            'climate' => 'Continental templado',
            'climate_temp' => '10 a 30°C',
            'climate_wind' => 'Vientos moderados de valle',
            'climate_precip' => 'Estacional, inviernos secos',
            'buildings' => 'Coliseo de la Celestial (251 pisos), Sitio de Examen del Cazador (Subterráneo), Estación Central de Trenes',
            'defenses' => 'Seguridad privada del Coliseo, policía metropolitana armada, cazadores con Nen contratados',
            'resources' => 'Servicios comerciales masivos, tecnología, entrenamiento en artes marciales',
            'coord_x' => 400,
            'coord_y' => 300,
            'base_danger' => 2,
        ],
        'yorknew' => [
            'preferred_fid' => 6,
            'disporder' => 3,
            'name' => 'Yorknew City',
            'region_slug' => 'yorknew',
            'country' => 'República de Padokea',
            'travel_difficulty' => 2,
            'island_image' => 'images/game/locations/yorknew.svg',
            'leader_name' => 'Líder de la Mafia de la Comunidad',
            'description' => 'Una colosal metrópolis costera de rascacielos infinitos. Es mundialmente conocida por albergar las mayores subastas anuales del mundo y por ser controlada por la Mafia de la Comunidad y la sombra del Genei Ryodan.',
            'terrain' => 'Metrópolis urbana costera, alcantarillas masivas, rascacielos',
            'climate' => 'Templado húmedo',
            'climate_temp' => '8 a 26°C',
            'climate_wind' => 'Vientos costeros del norte',
            'climate_precip' => 'Frecuente en otoño',
            'buildings' => 'Edificio de Subastas de la Southernpiece, Mansión de los Nostrade, Cementerio de Yorknew',
            'defenses' => 'Fuerzas especiales de la mafia (Inju / Bestias Sombrías), cuerpo de mercenarios contratados con Nen',
            'resources' => 'Objetos raros de subasta, información del mercado negro, dinero, tecnología avanzada',
            'coord_x' => 500,
            'coord_y' => 450,
            'base_danger' => 3,
        ],
        'ngl' => [
            'preferred_fid' => 7,
            'disporder' => 4,
            'name' => 'Neo-Green Life (NGL)',
            'region_slug' => 'ngl',
            'country' => 'NGL (Neo-Green Life)',
            'travel_difficulty' => 4,
            'island_image' => 'images/game/locations/ngl.svg',
            'leader_name' => 'Gyro',
            'description' => 'Un estado autónomo cerrado que prohíbe todo tipo de tecnología moderna e importaciones no biológicas. Escondía una red de producción de droga (D2) y fue el epicentro del brote de las Hormigas Quimera.',
            'terrain' => 'Bosques vírgenes impenetrables, ríos salvajes, cavernas profundas',
            'climate' => 'Tropical lluvioso',
            'climate_temp' => '20 a 35°C',
            'climate_wind' => 'Nulo en densa selva',
            'climate_precip' => 'Extrema, lluvias tropicales diarias',
            'buildings' => 'Aldeas ecológicas, Fábrica subterránea de D2, Nido de las Hormigas Quimera',
            'defenses' => 'Patrullas ecológicas armadas (arcos/flechas), Hormigas Quimera mutantes con Nen',
            'resources' => 'Fauna y flora exótica única, madera biológica, plantas medicinales, narcóticos ilegales',
            'coord_x' => 150,
            'coord_y' => 600,
            'base_danger' => 4,
        ],
    ];
}
