name: Subir al Servidor FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Despliegue FTP
    runs-on: ubuntu-latest
    steps:
    - name: Obtener el código
      uses: actions/checkout@v4

    - name: Subir archivos al servidor
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # NOTA: Si tu servidor requiere subir todo dentro de una carpeta
        # específica (como public_html o www), quita el símbolo '#' de la
        # siguiente línea y pon la ruta correcta de tu hosting:
        # server-dir: /public_html/
